{% set name = "py2puml" %}
{% set version = "0.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/py2puml-{{ version }}.tar.gz
  sha256: a6d126e9d964be9375f7837430b3f56320c5a33e067082d2a0b4fc071b710103

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  entry_points:
    - py2puml = py2puml.cli:run

requirements:
  host:
    - python >=3.8,<4.0
    - poetry >=0.12
    - poetry-core
    - pip
  run:
    - python >=3.8.0,<4.0.0

test:
  imports:
    - py2puml
  commands:
    - pip check
    - py2puml --version
  requires:
    - pip

about:
  home: https://github.com/lucsorel/py2puml
  summary: Generate PlantUML class diagrams to document your Python application.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - julian-belina
